### ISSUE TITLE
failed to load source for a dependency on `lang_tester`

### ISSUE THREAD

**Issue by azhai** [jazz-lang/Jazz#7]
env: Fedora Server 30, gcc-9.1

When I run "cargo build --release"

error: failed to load source for a dependency on `lang_tester`

Caused by:
  Unable to update https://github.com/softdevteam/lang_tester?branch=integer_exit_codes

Caused by:
  failed to find branch `integer_exit_codes`

Caused by:
  cannot locate local branch 'integer_exit_codes'; class=Reference (4); code=NotFound (-3)

**Comment by playXE** [comment]
Seems this branch merged,I will update Cargo.toml when I be on my PC

**Comment by playXE** [comment]
Updated Cargo.toml from my phone,but tests still not updated

**Comment by playXE** [comment]
Everything works now. Closing
