### ISSUE TITLE
project name conflict and domains

### ISSUE THREAD

**Issue by nikodemus** [jazz-lang/Jazz#8]
I feel like a douche saying this, but we have a conflict.

I have a long-running programming language project called jazzlang and I've been holding onto the domains jazzlang.(com|net|org) for it, waiting for the day that I arrive at an iteration I'm actually happy with. Never got there yet, so never made it public.

(I do NOT have the jazz-lang.* domains, and am not grabbing them because that would be a crappy move.)

I'm attached to the name, but I don't want to fight over it and am willing to transfer the domains if you're actually going to hold onto them and commit to your project.

What I would absolutely hate to see happen is handing them over and seeing jazzlight go dormant in twelve months. Of course life is life and as such unpredictable, and there are no guarantees ever.

I should also note that this is not an urgent issue - I'm not about to publish my language just now.

**Comment by playXE** [comment]
Hello and thanks for this "issue". I know that there are a lot of languages that got name "Jazz": [Why doesn’t a programming language named Jazz exist? Isn’t it a very cool name for a language?](https://www.quora.com/Why-doesn-t-a-programming-language-named-Jazz-exist-Isn-t-it-a-very-cool-name-for-a-language). But all projects listed in that topic doesn't look alive.
Now I actively rewriting Jazz in C++. I will publish new sources in the next couple of weeks. I don't have any plans for a website for the project now. But if this project will be popular I will add a proper website with online playground and other stuff related to the programming language.


I started this project in 2017 as a register-based VM and dynamically typed language. I developed this project for a school project and then in 2018 published sources  [Jazz](https://github.com/playXE/Jazz).  

> What I would absolutely hate to see happen is handing them over and seeing jazz light go dormant in twelve months. Of course, life is life and as such unpredictable, and there are no guarantees ever.


JazzLight and Jazz are not dead, I will rewrite JazzLight language in Jazz when Jazz will be ready to use and I believe that I will write a self-hosted version of Jazz compiler.  If you do not believe that the language is alive you can read my "posts" and messages in discord channel of [Programming language design](https://www.proglangdesign.net/) community. I can say that I'm not sure I want to change the name for the language.

**Comment by nikodemus** [comment]
Fair enough :)

I've cancelled autorenewal for the domains, let me know if you want them transferred before they expire in November. You can reach me directly at nikodemus at random-state.net.

Best of luck with the project!
